import * as fs from "fs";
import * as path from "path";
import chalk from "chalk";
import ora from "ora";
import { getCliperDir } from "../scope/config";

type Model = "claude" | "chatgpt";

interface AnalyzeOptions {
    model: string;
}

const CLAUDE_SYSTEM = `You are an expert software architect analyzing a codebase context document.
Your job is to transform raw codebase data into a highly optimized prompt for a Claude AI coding session.

Claude thinks best when given:
- Clear project narrative (what it is, why it exists)
- Explicit constraints and existing decisions to respect
- The specific area of focus with surrounding context
- What NOT to change or break
- Open questions or uncertainties the developer has

Your output must be a ready-to-paste prompt. No preamble. No explanation. Just the prompt itself.`;

const CHATGPT_SYSTEM = `You are an expert software architect analyzing a codebase context document.
Your job is to transform raw codebase data into a highly optimized prompt for a ChatGPT coding session.

ChatGPT works best when given:
- Numbered, structured context sections
- Explicit file paths and code blocks
- Clear task definition separated from context
- Constraints listed as bullet points
- A direct question or task at the end

Your output must be a ready-to-paste prompt. No preamble. No explanation. Just the prompt itself.`;

const CLAUDE_USER = (contextDoc: string) => `Here is the raw codebase context document generated by Cliper:

<context>
${contextDoc}
</context>

Transform this into an optimized Claude prompt following these rules:

CRITICAL ACCURACY RULES:
- Never expand acronyms unless the context doc explicitly defines them. If you see "SPEL" and the doc doesn't say what it stands for, write "SPEL" — do not invent an expansion.
- Never infer what a framework "is based on" from inspiration references. "Inspired by Anchor for Solana" does NOT mean the project runs on Solana.
- Include ALL macros and annotations found in the source code, not just the most common ones. If you see #[require_admin], include it.
- If a file was truncated, note that there may be additional macros or patterns not visible.

FORMAT RULES:
1. Opens with a concise project narrative (2-3 sentences max) — only state facts explicitly in the context doc
2. Summarizes the current branch focus and recent work
3. Lists key architectural decisions already made that must be respected
4. Highlights the most important files and their roles
5. Lists ALL macros/annotations found across all files
6. Surfaces any detected gaps the developer should be aware of
7. Ends with: "## What I need help with today:"

Make it feel like a natural briefing. Never invent details not present in the context doc.`;

const CHATGPT_USER = (contextDoc: string) => `Here is the raw codebase context document generated by Cliper:

${contextDoc}

Transform this into an optimized chatgpt prompt following these rules:

CRITICAL ACCURACY RULES:
- Never expand acronyms unless the context doc explicitly defines them. If you see "SPEL" and the doc doesn't say what it stands for, write "SPEL" — do not invent an expansion.
- Never infer what a framework "is based on" from inspiration references. "Inspired by Anchor for Solana" does NOT mean the project runs on Solana.
- Include ALL macros and annotations found in the source code, not just the most common ones. If you see #[require_admin], include it.
- If a file was truncated, note that there may be additional macros or patterns not visible.

FORMAT RULES:
1. Starts with "## Project Context" as a header
2. Uses numbered sections for: Project Overview, Tech Stack, Current Branch & Focus, Key Files, Constraints & Decisions, Known Gaps
3. Uses bullet points and code blocks for file paths and snippets
4. Keeps each section concise — no more than 5 bullet points per section
5. Ends with "## Task:" followed by a blank line for the developer to fill in

Format it for maximum clarity and scannability. ChatGPT responds best to structured, explicitly labeled context.`;

async function callAnthropicAPI(contextDoc: string): Promise<string> {
    const response = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "x-api-key": process.env.ANTHROPIC_API_KEY ?? "",
            "anthropic-version": "2023-06-01",
        },
        body: JSON.stringify({
            model: "claude-sonnet-4-20250514",
            max_tokens: 2000,
            system: CLAUDE_SYSTEM,
            messages: [{ role: "user", content: CLAUDE_USER(contextDoc) }],
        }),
    });

    if (!response.ok) {
        const err = await response.text();
        throw new Error(`Anthropic API error: ${response.status} — ${err}`);
    }

    const data = await response.json() as any;
    return data.content?.[0]?.text ?? "";
}

async function callOpenAIAPI(contextDoc: string): Promise<string> {
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${process.env.OPENAI_API_KEY ?? ""}`,
        },
        body: JSON.stringify({
            model: "gpt-4o",
            max_tokens: 2000,
            messages: [
                { role: "system", content: CHATGPT_SYSTEM },
                { role: "user", content: CHATGPT_USER(contextDoc) },
            ],
        }),
    });

    if (!response.ok) {
        const err = await response.text();
        throw new Error(`OpenAI API error: ${response.status} — ${err}`);
    }

    const data = await response.json() as any;
    return data.choices?.[0]?.message?.content ?? "";
}

export async function analyzeCommand(options: AnalyzeOptions): Promise<void> {
    const projectRoot = process.cwd();
    const cliperDir = getCliperDir(projectRoot);
    const contextPath = path.join(cliperDir, "context.md");

    // Check context doc exists
    if (!fs.existsSync(contextPath)) {
        console.error(chalk.red("\n  No context doc found. Run cliper init first.\n"));
        process.exit(1);
    }

    const contextDoc = fs.readFileSync(contextPath, "utf-8");
    const model = options.model.toLowerCase() as Model;

    // Validate model choice
    if (!["claude", "chatgpt"].includes(model)) {
        console.error(chalk.red(`\n  Unknown model: ${options.model}`));
        console.error(chalk.gray("  Usage: cliper analyze --model claude"));
        console.error(chalk.gray("         cliper analyze --model chatgpt\n"));
        process.exit(1);
    }

    // Check API key
    if (model === "claude" && !process.env.ANTHROPIC_API_KEY) {
        console.error(chalk.red("\n  ANTHROPIC_API_KEY not set."));
        console.error(chalk.gray("  Export it first: export ANTHROPIC_API_KEY=your_key_here\n"));
        process.exit(1);
    }

    if (model === "chatgpt" && !process.env.OPENAI_API_KEY) {
        console.error(chalk.red("\n  OPENAI_API_KEY not set."));
        console.error(chalk.gray("  Export it first: export OPENAI_API_KEY=your_key_here\n"));
        process.exit(1);
    }

    console.log(chalk.bold.cyan(`\n  cliper analyze — ${model}\n`));

    const spinner = ora(`Analyzing context doc with ${model === "claude" ? "Claude" : "ChatGPT"}...`).start();

    try {
        let prompt: string;

        if (model === "claude") {
            prompt = await callAnthropicAPI(contextDoc);
            const outputPath = path.join(cliperDir, "prompt-claude.md");
            fs.writeFileSync(outputPath, prompt, "utf-8");
            spinner.succeed(chalk.green("Claude prompt generated"));
            console.log(chalk.gray(`\n  Saved: ${outputPath}\n`));
            console.log(chalk.cyan("  Copy to clipboard:"));
            console.log(chalk.white("    cliper analyze --model claude | pbcopy\n"));
            console.log(chalk.cyan("  Or open directly:"));
            console.log(chalk.white(`    cat ${outputPath} | pbcopy\n`));
        } else {
            prompt = await callOpenAIAPI(contextDoc);
            const outputPath = path.join(cliperDir, "prompt-gpt.md");
            fs.writeFileSync(outputPath, prompt, "utf-8");
            spinner.succeed(chalk.green("ChatGPT prompt generated"));
            console.log(chalk.gray(`\n  Saved: ${outputPath}\n`));
            console.log(chalk.cyan("  Copy to clipboard:"));
            console.log(chalk.white(`    cat ${outputPath} | pbcopy\n`));
        }

    } catch (err: any) {
        spinner.fail(chalk.red("Analysis failed"));
        console.error(chalk.red(`\n  ${err.message}\n`));
        process.exit(1);
    }
}